### ISSUE TITLE
FTP Server issue with android.

### ISSUE THREAD

**Issue by Chaaang** [abdelaziz-mahdy/ftp_server#9]
When I start the server and test it using filezilla, it gives me error. 
![image](https://github.com/user-attachments/assets/a86f3b67-2cb7-47a2-9934-912a92e43cdb)
![image](https://github.com/user-attachments/assets/a18176c4-92cf-42eb-8c5d-4e24e228850b)

I copy the code in the "example" to test it out first before using it in my application. (I use real device for testing)

**Comment by abdelaziz-mahdy** [comment]
I didn't give filezila a try and looks like it's using an extension I didn't add, will check it and let you know

**Comment by abdelaziz-mahdy** [comment]
you are using filezila on windows right? 

since i just tested on macos and it works correctly, so i need to have the same setup as you

**Comment by abdelaziz-mahdy** [comment]
macos to macos filezila works
macos to windows filezila works
android to windows filezila doesnt work (but because of a different error than the one you mentioned ) and fixed it

so i think it has something to do with username or password did it have any weird chars? like ones that outside of utf8?

since i am seeing `Server does not support non-ASCII characters.` in filezila so i will look into this problem

**Comment by Chaaang** [comment]
I didn't put any username or password since this is for testing. Thank you!

**Comment by abdelaziz-mahdy** [comment]
i fixed all of the problems related to filezila, but your problem didnt happen to me, so i added more details about the log of the error 

check with the last version `ftp_server: ^1.0.3`

**Comment by Chaaang** [comment]
Hi! Thanks already tested it and it works. 🙌🏻
